# application.properties
server.port=${MAVEN_BACKEND_PORT}       
server.address=0.0.0.0

# spring.datasource.url=${DB_URL}
# spring.datasource.username=${DB_USERNAME}
# spring.datasource.password=${DB_PASSWORD}

# URL kết nối tới MySQL (jdbcUrl)
spring.datasource.url=${DB_URL}

# Thông tin xác thực (username, password)
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


# (Optional) driver class name, thường Spring Boot tự detect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate DDL auto (none/validate/update/create)
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

# Thời gian chờ lấy connection đầu tiên (ms). Mặc định 1s = 1000ms.
spring.datasource.hikari.connection-timeout=30000

# pool size Hikari
spring.datasource.hikari.maximumPoolSize=10
spring.datasource.hikari.minimumIdle=1


